# Generated by Django 4.0.5 on 2022-06-28 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Libro',
            new_name='Book',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='titulo',
            new_name='title',
        ),
    ]
